adjustments to bunsenlabs-session for wayland  This includes conditions in autostart  Thare are also some helper scripts and configs included

diff --git a/bin/bunsenlabs-session b/bin/bunsenlabs-session
--- a/bin/bunsenlabs-session
+++ b/bin/bunsenlabs-session
@@ -7,6 +7,14 @@ if test -n "$1"; then
   exit
 fi
 
+W=false
+
+# check who calls here
+case $0 in
+    *bunsenlabs-wayland-session)W=true
+    ;;
+esac
+
 usr_confdir="${XDG_CONFIG_HOME:-$HOME/.config}"
 usr_autostart="$usr_confdir/bunsen/autostart"
 usr_envfile="$usr_confdir/bunsen/environment"
@@ -18,9 +26,11 @@ default_autostart='/usr/share/bunsen/skel/.config/bunsen/autostart'
 bl_autostart='/usr/lib/bunsen/configs/bunsen-autostart'
 
 # Clean up after GDM (GDM sets the number of desktops to one).
-xprop -root -remove _NET_NUMBER_OF_DESKTOPS \
+if [ "$W" = 'false' ]; then
+    xprop -root -remove _NET_NUMBER_OF_DESKTOPS \
       -remove _NET_DESKTOP_NAMES \
       -remove _NET_CURRENT_DESKTOP 2> /dev/null
+fi
 
 # This section is only executed on first boot.
 if [ ! -e "$usr_setupflagfile" ]
@@ -37,12 +47,16 @@ then
 
     # Merge ~/.Xresources
     # (usually done by /etc/X11/Xsession.d/30x11-common_xresources)
-    test -r "$usr_resources" && xrdb -merge "$usr_resources" || echo "$0: cannot merge $usr_resources" >&2
+    if [ "$W" = 'false' ]; then
+        test -r "$usr_resources" && xrdb -merge "$usr_resources" || echo "$0: cannot merge $usr_resources" >&2
+    fi
 
     # Set up the user environment for X sessions.
     # (usually sourced by /etc/X11/Xsession.d/40x11-common_xsessionrc)
-    test -r "$usr_xsessionrc" && . "$usr_xsessionrc" || echo "$0: cannot source $usr_xsessionrc" >&2
-
+    if [ "$W" = 'false' ]; then
+        test -r "$usr_xsessionrc" && . "$usr_xsessionrc" || echo "$0: cannot source $usr_xsessionrc" >&2
+    fi
+    
     # Set up user directories
     # (usually run by /etc/X11/Xsession.d/60xdg-user-dirs-update)
     if [ -x /usr/bin/xdg-user-dirs-update ]; then
@@ -61,7 +75,11 @@ test -r "$usr_envfile" && . "$usr_envfile" || echo "$0: cannot source $usr_envfi
 
 # Check if user has set an alternative window manager.
 # This would be the first setting in ~/.config/bunsen/autostart.
-win_man=openbox
+if [ "$W" = 'false' ]; then 
+    win_man=openbox
+else
+    win_man=labwc
+fi
 # just use first uncommented line of file, then break
 [ -r "$usr_autostart" ] && {
     while read -r first rest
@@ -77,6 +95,11 @@ win_man=openbox
         break
     done < "$usr_autostart"
 }
+
+# if default window_manager=openbox in $usr_autostart on condition of $W = true we set to labwc
+if [ "$W" = true ] && [ "$win_man" = 'openbox' ]; then
+    win_man=labwc
+fi
 
 hash "$win_man" 2>/dev/null || { echo "$0: Window manager command \"$win_man\" not found" >&2; exit 1;}
 
